"""
PINN training for 1D blood flow bifurcation (parent + 2 daughters)
Uses DeepXDE + PyTorch.

Trains on data from blood_flow_data.csv (generated by solver.py).
Physics: 1D continuity + momentum + tube law.
"""

import numpy as np
import pandas as pd
import deepxde as dde
import torch
import os

# ============================================================
# STAŁE FIZYCZNE (muszą być zgodne z solver.py)
# ============================================================
rho = 1060.0
mu = 4.0e-3
KR = 8.0 * np.pi * mu / rho

L_p, r_p = 0.10, 0.005
L_d1, r_d1 = 0.08, 0.0035
L_d2, r_d2 = 0.09, 0.0040
c0 = 5.0

A0_p = np.pi * r_p**2
A0_d1 = np.pi * r_d1**2
A0_d2 = np.pi * r_d2**2

beta_p = (4.0 / 3.0) * np.sqrt(np.pi) * rho * c0**2 * A0_p
beta_d1 = (4.0 / 3.0) * np.sqrt(np.pi) * rho * c0**2 * A0_d1
beta_d2 = (4.0 / 3.0) * np.sqrt(np.pi) * rho * c0**2 * A0_d2

T_out = 0.75

# ============================================================
# WCZYTANIE DANYCH
# ============================================================
print("Wczytywanie blood_flow_data.csv...")
df = pd.read_csv("blood_flow_data.csv")

df_p = df[df["vessel"] == "parent"].copy()
df_d1 = df[df["vessel"] == "daughter1"].copy()
df_d2 = df[df["vessel"] == "daughter2"].copy()

def normalize_z(df_seg, L):
    z_norm = df_seg["z"].values / L
    return df_seg.assign(z_norm=z_norm)

df_p = normalize_z(df_p, L_p)
df_d1 = normalize_z(df_d1, L_d1)
df_d2 = normalize_z(df_d2, L_d2)

df_p["vessel_id"] = 0
df_d1["vessel_id"] = 1
df_d2["vessel_id"] = 2

df_all = pd.concat([df_p, df_d1, df_d2], ignore_index=True)
n_total = len(df_all)
print(f"  Łącznie {n_total} punktów danych")

# Subsamplowanie
subsample = 50  # weź co 50-ty punkt (16k punktów)
df_train = df_all.iloc[::subsample].reset_index(drop=True)
n_train = len(df_train)
print(f"  Po subsamplingu (co {subsample}): {n_train} punktów")

# ============================================================
# OBSERWACJE
# ============================================================
t_obs = df_train["t"].values.astype(np.float64)
z_obs = df_train["z_norm"].values.astype(np.float64)
vessel_id = df_train["vessel_id"].values.astype(np.int32)
A_obs = df_train["A"].values.astype(np.float64)
Q_obs = df_train["Q"].values.astype(np.float64)

vessel_onehot = np.zeros((len(vessel_id), 3))
vessel_onehot[np.arange(len(vessel_id)), vessel_id] = 1.0

X_obs = np.column_stack([t_obs, z_obs, vessel_onehot.astype(np.float64)])
y_obs = np.column_stack([A_obs, Q_obs])

# ============================================================
# GEOMETRIA + PDE
# ============================================================
geom = dde.geometry.Hypercube([0, 0, 0, 0, 0],
                               [T_out, 1.0, 1, 1, 1])


def pde_fn(x, y):
    """
    x: (t, z_norm, onehot_0, onehot_1, onehot_2)
    y: (A, Q)
    """
    A, Q = y[:, 0:1], y[:, 1:2]

    A_t = dde.grad.jacobian(y, x, i=0, j=0)
    Q_t = dde.grad.jacobian(y, x, i=1, j=0)
    A_z = dde.grad.jacobian(y, x, i=0, j=1)
    Q_z = dde.grad.jacobian(y, x, i=1, j=1)

    onehot = x[:, 2:5]
    A0 = (A0_p * onehot[:, 0:1] + A0_d1 * onehot[:, 1:2] + A0_d2 * onehot[:, 2:3]).detach()
    beta = (beta_p * onehot[:, 0:1] + beta_d1 * onehot[:, 1:2] + beta_d2 * onehot[:, 2:3]).detach()
    L = (L_p * onehot[:, 0:1] + L_d1 * onehot[:, 1:2] + L_d2 * onehot[:, 2:3]).detach()

    # Continuity: dA/dt + (1/L)*dQ/dz = 0
    F_A = A_t + Q_z / L

    # Momentum: dQ/dt + d(Q²/A)/dz + A/ρ * dP/dz + KR*Q/A = 0
    dF2_dz = (2.0 * Q / A * Q_z - Q**2 / A**2 * A_z) / L
    dP_dz = beta / (2.0 * A0 * torch.sqrt(torch.clamp(A, min=1e-12))) * A_z / L
    viscous = KR * Q / A

    F_Q = Q_t + dF2_dz + A / rho * dP_dz + viscous
    return [F_A, F_Q]


# ============================================================
# SIEC
# ============================================================
net = dde.nn.FNN(
    layer_sizes=[5, 128, 128, 128, 128, 2],
    activation="tanh",
    kernel_initializer="Glorot normal"
)

# ============================================================
# MODEL: PDE bez BC
# ============================================================
data = dde.data.PDE(
    geom,
    pde_fn,
    [],              # brak BC
    num_domain=10000,
    num_boundary=0,
    solution=None,
    num_test=2000
)

model = dde.Model(data, net)

# ============================================================
# TRENING WŁASNY Z DANYMI
# ============================================================
# DeepXDE nie ma wbudowanej obsługi dodawania obserwacji do PDE,
# więc trenujemy w dwóch krokach:
# 1. Najpierw pre-trening na samych danych (supervised)
# 2. Potem fine-tuning z PDE

print("\nKrok 1: Pre-trening na danych (supervised)")
print(f"  Wejścia: t, z_norm, onehot[3] -> 5")
print(f"  Wyjścia: A, Q -> 2")
print(f"  Punkty: {n_train}")
print()

# Użyjemy DataSet dla supervised pretrain
data_supervised = dde.data.DataSet(
    X_train=X_obs, y_train=y_obs,
    X_test=X_obs[:1000], y_test=y_obs[:1000],
    standardize=False
)

model_sup = dde.Model(data_supervised, net)

# Adam na danych
model_sup.compile("adam", lr=1e-3, loss="MSE")
losshistory, train_state = model_sup.train(iterations=15000, display_every=1000)

# L-BFGS na danych
model_sup.compile("L-BFGS", loss="MSE")
losshistory, train_state = model_sup.train(iterations=15000, display_every=1000)

print("\nKrok 2: Fine-tuning z PDE + dane")
print("  Używamy oryginalnego modelu PDE z tą samą siecią\n")

# Teraz trenujemy model PDE (wykorzystuje tę samą sieć)
model.compile("adam", lr=1e-4, loss="MSE")
# na samym PDE (bez danych)
losshistory, train_state = model.train(iterations=10000, display_every=500)

print("\nKrok 3: Końcowa ocena")
print()

# ============================================================
# EWALUACJA
# ============================================================
print("Ewaluacja na danych treningowych...")
y_pred = model.predict(X_obs)
A_pred = y_pred[:, 0]
Q_pred = y_pred[:, 1]

err_A = np.abs(A_pred - A_obs) / (np.max(A_obs) - np.min(A_obs) + 1e-12)
err_Q = np.abs(Q_pred - Q_obs) / (np.max(Q_obs) - np.min(Q_obs) + 1e-12)

print(f"  Normalizowany błąd A: mean={np.mean(err_A):.4f}, max={np.max(err_A):.4f}")
print(f"  Normalizowany błąd Q: mean={np.mean(err_Q):.4f}, max={np.max(err_Q):.4f}")
print()

# ============================================================
# ZAPIS MODELU
# ============================================================
model.save("pinn_blood_flow_model")
print("Model zapisany jako pinn_blood_flow_model")

# ============================================================
# PREDYKCJA
# ============================================================
print("\nGenerowanie predykcji na siatce...")
Nt_grid = 100
Nz_grid = 50
t_grid = np.linspace(0, T_out, Nt_grid)
z_norm = np.linspace(0, 1, Nz_grid)

rows = []
for i, t_val in enumerate(t_grid):
    for z_val in z_norm:
        for vid, (L, name) in enumerate([
            (L_p, "parent"), (L_d1, "daughter1"), (L_d2, "daughter2")
        ]):
            onehot = [1, 0, 0] if vid == 0 else ([0, 1, 0] if vid == 1 else [0, 0, 1])
            x_in = np.array([[t_val, z_val, *onehot]], dtype=np.float64)
            y_out = model.predict(x_in)
            rows.append([t_val, z_val * L, name, float(y_out[0, 0]), float(y_out[0, 1])])

    if (i + 1) % 25 == 0:
        print(f"  Predykcja: {i+1}/{Nt_grid}")

df_pred = pd.DataFrame(rows, columns=["t", "z", "vessel", "A", "Q"])
df_pred.to_csv("pinn_prediction.csv", index=False)
print("Zapisano pinn_prediction.csv")

print("\nGotowe!")