"""
PINN training for 1D blood flow bifurcation (parent + 2 daughters)
Uses DeepXDE + PyTorch.

Trains on data from blood_flow_data.csv (generated by solver.py).
Physics: 1D continuity + momentum + tube law.
Boundary conditions based on:
  D. Kim, J. Tithof. "One-Dimensional Modeling of Blood Flow:
  A Comprehensive Yet Concise Review" (2025) - sekcje 6, 7
"""

import numpy as np
import pandas as pd
import deepxde as dde
import torch
import os

dde.config.set_default_float("float64")
torch.set_default_dtype(torch.float64)

# ============================================================
# STAŁE FIZYCZNE (muszą być zgodne z solver.py)
# ============================================================
rho = 1060.0
mu = 4.0e-3
KR = 8.0 * np.pi * mu / rho

L_p, r_p = 0.10, 0.005
L_d1, r_d1 = 0.08, 0.0035
L_d2, r_d2 = 0.09, 0.0040
c0 = 5.0

A0_p = np.pi * r_p**2
A0_d1 = np.pi * r_d1**2
A0_d2 = np.pi * r_d2**2

beta_p = rho * c0**2 / A0_p
beta_d1 = rho * c0**2 / A0_d1
beta_d2 = rho * c0**2 / A0_d2

T_out = 0.75

# Stałe dla warunków brzegowych
c0_p = np.sqrt(beta_p * A0_p / rho)
c0_d1 = np.sqrt(beta_d1 * A0_d1 / rho)
c0_d2 = np.sqrt(beta_d2 * A0_d2 / rho)

# W2_0 = u_0 - 2*c0, u_0 = 0 (spoczynek)
W2_0_p = -2.0 * c0_p
W2_0_d1 = -2.0 * c0_d1
W2_0_d2 = -2.0 * c0_d2

T_pulse = 0.02  # szerokość impulsu w Q_in(t)
Q_peak = 5e-5

# Normalizacja wejść/wyjść
T_scale = T_out
A_scale = max(A0_p, A0_d1, A0_d2)
Q_scale = Q_peak

# ============================================================
# FUNKCJE POMOCNICZE
# ============================================================
def pressure(A, A0, beta):
    """P = beta*(A - A0)"""
    beta_t = torch.as_tensor(beta, dtype=A.dtype, device=A.device)
    A0_t = torch.as_tensor(A0, dtype=A.dtype, device=A.device)
    return beta_t * (A - A0_t)

def wave_speed(A, A0, beta):
    """c = sqrt(beta * A / rho)"""
    beta_t = torch.as_tensor(beta, dtype=A.dtype, device=A.device)
    rho_t = torch.as_tensor(rho, dtype=A.dtype, device=A.device)
    return torch.sqrt(beta_t * A / rho_t)

def total_pressure(A, Q, A0, beta):
    """P_tot = P + 0.5*rho*(Q/A)^2"""
    rho_t = torch.as_tensor(rho, dtype=A.dtype, device=A.device)
    return pressure(A, A0, beta) + 0.5 * rho_t * (Q / torch.clamp(A, min=1e-12))**2

def riemann_W1(A, Q, A0, beta):
    """W1 = u + 2*c"""
    u = Q / torch.clamp(A, min=1e-12)
    c = wave_speed(A, A0, beta)
    return u + 2.0 * c

def riemann_W2(A, Q, A0, beta):
    """W2 = u - 2*c"""
    u = Q / torch.clamp(A, min=1e-12)
    c = wave_speed(A, A0, beta)
    return u - 2.0 * c

def Q_in_waveform(t):
    """Przebieg Q_in(t) zgodny z solver.py"""
    out = torch.zeros_like(t)
    mask1 = (t <= T_pulse)
    mask2 = (t >= 0.1) & (t <= 0.1 + T_pulse)
    out = out + mask1 * (Q_peak * torch.sin(np.pi * t / T_pulse))
    out = out + mask2 * (Q_peak * torch.sin(np.pi * (t - 0.1) / T_pulse))
    return out

def denorm_output(y_hat):
    """Zwraca (A, Q) w jednostkach fizycznych."""
    A = y_hat[:, 0:1] * A_scale
    Q = y_hat[:, 1:2] * Q_scale
    return A, Q

# ============================================================
# WCZYTANIE DANYCH
# ============================================================
print("Wczytywanie blood_flow_data.csv...")
df = pd.read_csv("blood_flow_data.csv")

df_p = df[df["vessel"] == "parent"].copy()
df_d1 = df[df["vessel"] == "daughter1"].copy()
df_d2 = df[df["vessel"] == "daughter2"].copy()

def normalize_z(df_seg, L):
    z_norm = df_seg["z"].values / L
    return df_seg.assign(z_norm=z_norm)

df_p = normalize_z(df_p, L_p)
df_d1 = normalize_z(df_d1, L_d1)
df_d2 = normalize_z(df_d2, L_d2)

df_p["vessel_id"] = 0
df_d1["vessel_id"] = 1
df_d2["vessel_id"] = 2

df_all = pd.concat([df_p, df_d1, df_d2], ignore_index=True)
n_total = len(df_all)
print(f"  Łącznie {n_total} punktów danych")

# Subsamplowanie
subsample = 50  # weź co 50-ty punkt
df_train = df_all.iloc[::subsample].reset_index(drop=True)
n_train = len(df_train)
print(f"  Po subsamplingu (co {subsample}): {n_train} punktów")

# ============================================================
# OBSERWACJE
# ============================================================
t_obs = (df_train["t"].values.astype(np.float64)) / T_scale
z_obs = df_train["z_norm"].values.astype(np.float64)
vessel_id = df_train["vessel_id"].values.astype(np.int32)
A_obs = df_train["A"].values.astype(np.float64)
Q_obs = df_train["Q"].values.astype(np.float64)

vessel_onehot = np.zeros((len(vessel_id), 3))
vessel_onehot[np.arange(len(vessel_id)), vessel_id] = 1.0

X_obs = np.column_stack([t_obs, z_obs, vessel_onehot.astype(np.float64)])
y_obs = np.column_stack([A_obs / A_scale, Q_obs / Q_scale])

# ============================================================
# PUNKTY DLA WARUNKÓW BRZEGOWYCH
# ============================================================
N_bc_time = 200
t_bc = np.linspace(0, T_out, N_bc_time).astype(np.float64)
t_bc_norm = t_bc / T_scale

# --- 1. Inlet BC: parent, z=0 ---
# Q(t, z=0, vessel=parent) = Q_in(t)
X_inlet = np.column_stack([
    t_bc_norm,
    np.zeros(N_bc_time, dtype=np.float64),        # z = 0 (z_norm)
    np.ones(N_bc_time, dtype=np.float64) * 1.0,    # onehot[0] = 1
    np.zeros(N_bc_time, dtype=np.float64),          # onehot[1] = 0
    np.zeros(N_bc_time, dtype=np.float64),          # onehot[2] = 0
])
Q_inlet_target = np.zeros((N_bc_time, 1), dtype=np.float64)
for i in range(N_bc_time):
    t_val = t_bc[i]
    if t_val <= T_pulse:
        Q_inlet_target[i, 0] = Q_peak * np.sin(np.pi * t_val / T_pulse)
    elif 0.1 <= t_val <= 0.1 + T_pulse:
        Q_inlet_target[i, 0] = Q_peak * np.sin(np.pi * (t_val - 0.1) / T_pulse)
    else:
        Q_inlet_target[i, 0] = 0.0

# --- 2. Non-reflective outlet BC: daughter1, z=1 ---
X_outlet_d1 = np.column_stack([
    t_bc_norm,
    np.ones(N_bc_time, dtype=np.float64),          # z = 1
    np.zeros(N_bc_time, dtype=np.float64),          # onehot[0] = 0
    np.ones(N_bc_time, dtype=np.float64) * 1.0,    # onehot[1] = 1
    np.zeros(N_bc_time, dtype=np.float64),          # onehot[2] = 0
])

# --- 3. Non-reflective outlet BC: daughter2, z=1 ---
X_outlet_d2 = np.column_stack([
    t_bc_norm,
    np.ones(N_bc_time, dtype=np.float64),          # z = 1
    np.zeros(N_bc_time, dtype=np.float64),          # onehot[0] = 0
    np.zeros(N_bc_time, dtype=np.float64),          # onehot[1] = 0
    np.ones(N_bc_time, dtype=np.float64) * 1.0,    # onehot[2] = 1
])

# --- 4. Bifurcation junction ---
# Punkty po stronie parent (z=1) i daughter (z=0) w tych samych chwilach
# Dla każdego t, potrzebujemy parent(z=1), d1(z=0), d2(z=0)
X_junction_p = np.column_stack([
    t_bc_norm,
    np.ones(N_bc_time, dtype=np.float64),          # z = 1
    np.ones(N_bc_time, dtype=np.float64) * 1.0,    # onehot[0] = 1
    np.zeros(N_bc_time, dtype=np.float64),          # onehot[1] = 0
    np.zeros(N_bc_time, dtype=np.float64),          # onehot[2] = 0
])
X_junction_d1 = np.column_stack([
    t_bc_norm,
    np.zeros(N_bc_time, dtype=np.float64),          # z = 0
    np.zeros(N_bc_time, dtype=np.float64),          # onehot[0] = 0
    np.ones(N_bc_time, dtype=np.float64) * 1.0,    # onehot[1] = 1
    np.zeros(N_bc_time, dtype=np.float64),          # onehot[2] = 0
])
X_junction_d2 = np.column_stack([
    t_bc_norm,
    np.zeros(N_bc_time, dtype=np.float64),          # z = 0
    np.zeros(N_bc_time, dtype=np.float64),          # onehot[0] = 0
    np.zeros(N_bc_time, dtype=np.float64),          # onehot[1] = 0
    np.ones(N_bc_time, dtype=np.float64) * 1.0,    # onehot[2] = 1
])

# ============================================================
# GEOMETRIA + PDE
# ============================================================
geom = dde.geometry.Hypercube([0, 0, 0, 0, 0],
                               [1.0, 1.0, 1, 1, 1])


def pde_fn(x, y):
    """
    x: (t, z_norm, onehot_0, onehot_1, onehot_2)
    y: (A_hat, Q_hat)
    """
    A_hat, Q_hat = y[:, 0:1], y[:, 1:2]
    A = A_hat * A_scale
    Q = Q_hat * Q_scale

    A_hat_t = dde.grad.jacobian(y, x, i=0, j=0)
    Q_hat_t = dde.grad.jacobian(y, x, i=1, j=0)
    A_hat_z = dde.grad.jacobian(y, x, i=0, j=1)
    Q_hat_z = dde.grad.jacobian(y, x, i=1, j=1)

    onehot = x[:, 2:5]
    beta = (beta_p * onehot[:, 0:1] + beta_d1 * onehot[:, 1:2] + beta_d2 * onehot[:, 2:3]).detach()
    L = (L_p * onehot[:, 0:1] + L_d1 * onehot[:, 1:2] + L_d2 * onehot[:, 2:3]).detach()

    A_t = (A_scale / T_scale) * A_hat_t
    Q_t = (Q_scale / T_scale) * Q_hat_t
    A_z = (A_scale / L) * A_hat_z
    Q_z = (Q_scale / L) * Q_hat_z

    # Continuity: dA/dt + dQ/dz = 0 (pochodne w jednostkach fizycznych)
    F_A = A_t + Q_z

    # Momentum: dQ/dt + d(Q²/A)/dz + A/rho * dP/dz + KR*Q/A = 0
    dF2_dz = (2.0 * Q / A * Q_z - Q**2 / A**2 * A_z)
    dP_dz = beta * A_z
    viscous = KR * Q / A

    F_Q = Q_t + dF2_dz + A / rho * dP_dz + viscous
    return [F_A, F_Q]


# ============================================================
# SIEC
# ============================================================
net = dde.nn.FNN(
    layer_sizes=[5, 128, 128, 128, 128, 2],
    activation="tanh",
    kernel_initializer="Glorot normal"
)

# ============================================================
# MODEL: PDE bez BC (do pre-treningu)
# ============================================================
data = dde.data.PDE(
    geom,
    pde_fn,
    [],              # brak BC - dodamy je ręcznie
    num_domain=10000,
    num_boundary=0,
    solution=None,
    num_test=2000
)

model = dde.Model(data, net)

# ============================================================
# TRENING WŁASNY Z DANYMI + BC
# ============================================================
print("\nKrok 1: Pre-trening na danych (supervised)")
print(f"  Wejścia: t, z_norm, onehot[3] -> 5")
print(f"  Wyjścia: A, Q -> 2")
print(f"  Punkty: {n_train}")
print()

# Użyjemy DataSet dla supervised pretrain
data_supervised = dde.data.DataSet(
    X_train=X_obs, y_train=y_obs,
    X_test=X_obs[:1000], y_test=y_obs[:1000],
    standardize=False
)

model_sup = dde.Model(data_supervised, net)

# Adam na danych
model_sup.compile("adam", lr=1e-3, loss="MSE")
losshistory, train_state = model_sup.train(iterations=15000, display_every=1000)

# L-BFGS na danych
model_sup.compile("L-BFGS", loss="MSE")
losshistory, train_state = model_sup.train(iterations=15000, display_every=1000)

print("\nKrok 2: Fine-tuning z PDE + dane + BC")
print("  Używamy własnej pętli treningowej aby dodać BC\n")

# ============================================================
# WŁASNA PĘTLA TRENINGOWA Z BC
# ============================================================
# Konwertujemy dane na tensory PyTorch
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Punkty kolokacji PDE
N_colloc = 20000
N_colloc_each = N_colloc // 3
N_colloc_last = N_colloc - 2 * N_colloc_each

def sample_collocation(n_samples, onehot_vec):
    t = np.random.uniform(0.0, 1.0, size=(n_samples, 1))
    z = np.random.uniform(0.0, 1.0, size=(n_samples, 1))
    onehot = np.repeat(np.array(onehot_vec, dtype=np.float64)[None, :], n_samples, axis=0)
    return np.hstack([t, z, onehot])

X_colloc_np = np.vstack([
    sample_collocation(N_colloc_each, [1.0, 0.0, 0.0]),
    sample_collocation(N_colloc_each, [0.0, 1.0, 0.0]),
    sample_collocation(N_colloc_last, [0.0, 0.0, 1.0]),
])
X_colloc = torch.tensor(X_colloc_np, dtype=torch.float64, device=device, requires_grad=True)

# Dane obserwowane
X_obs_t = torch.tensor(X_obs, dtype=torch.float64, device=device)
y_obs_t = torch.tensor(y_obs, dtype=torch.float64, device=device)

# Punkty BC
X_inlet_t = torch.tensor(X_inlet, dtype=torch.float64, device=device)
Q_inlet_t = torch.tensor(Q_inlet_target, dtype=torch.float64, device=device)

X_outlet_d1_t = torch.tensor(X_outlet_d1, dtype=torch.float64, device=device)
X_outlet_d2_t = torch.tensor(X_outlet_d2, dtype=torch.float64, device=device)

X_junction_p_t = torch.tensor(X_junction_p, dtype=torch.float64, device=device)
X_junction_d1_t = torch.tensor(X_junction_d1, dtype=torch.float64, device=device)
X_junction_d2_t = torch.tensor(X_junction_d2, dtype=torch.float64, device=device)

# Pobieramy sieć PyTorch
pinn_net = model.net.to(device)
pinn_net.train()

# Funkcja straty PDE
def pde_loss_fn(x_colloc, net_model):
    x_colloc.requires_grad_(True)
    y_pred = net_model(x_colloc)
    A_hat, Q_hat = y_pred[:, 0:1], y_pred[:, 1:2]
    A = A_hat * A_scale
    Q = Q_hat * Q_scale

    # Gradienty
    A_hat_t = torch.autograd.grad(A_hat.sum(), x_colloc, create_graph=True)[0][:, 0:1]
    Q_hat_t = torch.autograd.grad(Q_hat.sum(), x_colloc, create_graph=True)[0][:, 0:1]
    A_hat_z = torch.autograd.grad(A_hat.sum(), x_colloc, create_graph=True)[0][:, 1:2]
    Q_hat_z = torch.autograd.grad(Q_hat.sum(), x_colloc, create_graph=True)[0][:, 1:2]

    onehot = x_colloc[:, 2:5]
    beta_val = (beta_p * onehot[:, 0:1].detach() + beta_d1 * onehot[:, 1:2].detach() + beta_d2 * onehot[:, 2:3].detach())
    L_val = (L_p * onehot[:, 0:1].detach() + L_d1 * onehot[:, 1:2].detach() + L_d2 * onehot[:, 2:3].detach())

    A_t = (A_scale / T_scale) * A_hat_t
    Q_t = (Q_scale / T_scale) * Q_hat_t
    A_z = (A_scale / L_val) * A_hat_z
    Q_z = (Q_scale / L_val) * Q_hat_z

    # Continuity
    F_A = A_t + Q_z

    # Momentum
    dF2_dz = (2.0 * Q / A * Q_z - Q**2 / A**2 * A_z)
    dP_dz = beta_val * A_z
    viscous = KR * Q / A

    F_Q = Q_t + dF2_dz + A / rho * dP_dz + viscous

    loss_pde = torch.mean(F_A**2) + torch.mean(F_Q**2)
    return loss_pde


# Funkcja straty BC
def bc_loss_fn(net_model):
    loss_bc = 0.0

    # 1. Inlet BC: Q(t, z=0, parent) = Q_in(t)
    y_inlet = net_model(X_inlet_t)
    _, Q_pred_inlet = denorm_output(y_inlet)
    loss_bc += torch.mean((Q_pred_inlet - Q_inlet_t)**2)

    # 2. Outlet BC (non-reflective): daughter1
    # W2 = u - 2*c = W2_0 = -2*c0
    y_out_d1 = net_model(X_outlet_d1_t)
    A_out_d1, Q_out_d1 = denorm_output(y_out_d1)
    W2_d1 = riemann_W2(A_out_d1, Q_out_d1, A0_d1, beta_d1)
    loss_bc += torch.mean((W2_d1 - W2_0_d1)**2)

    # 3. Outlet BC (non-reflective): daughter2
    y_out_d2 = net_model(X_outlet_d2_t)
    A_out_d2, Q_out_d2 = denorm_output(y_out_d2)
    W2_d2 = riemann_W2(A_out_d2, Q_out_d2, A0_d2, beta_d2)
    loss_bc += torch.mean((W2_d2 - W2_0_d2)**2)

    # 4. Bifurcation junction
    y_junc_p = net_model(X_junction_p_t)
    y_junc_d1 = net_model(X_junction_d1_t)
    y_junc_d2 = net_model(X_junction_d2_t)

    A_j_p, Q_j_p = denorm_output(y_junc_p)
    A_j_d1, Q_j_d1 = denorm_output(y_junc_d1)
    A_j_d2, Q_j_d2 = denorm_output(y_junc_d2)

    # 4a. Conservation of mass: Q_p = Q_d1 + Q_d2
    loss_bc += torch.mean((Q_j_p - Q_j_d1 - Q_j_d2)**2)

    # 4b. Total pressure continuity: P_tot_p = P_tot_d1
    P_tot_p = total_pressure(A_j_p, Q_j_p, A0_p, beta_p)
    P_tot_d1 = total_pressure(A_j_d1, Q_j_d1, A0_d1, beta_d1)
    P_tot_d2 = total_pressure(A_j_d2, Q_j_d2, A0_d2, beta_d2)
    loss_bc += torch.mean((P_tot_p - P_tot_d1)**2)
    loss_bc += torch.mean((P_tot_p - P_tot_d2)**2)

    return loss_bc


# Optymalizacja
optimizer = torch.optim.Adam(pinn_net.parameters(), lr=1e-4)

# Wagi strat
w_data = 1.0
w_pde = 0.1
w_bc = 0.5

N_iter = 20000
print(f"  Training for {N_iter} iterations...")
print(f"  Weights: data={w_data}, pde={w_pde}, bc={w_bc}")
print()

for it in range(N_iter):
    optimizer.zero_grad()

    # Data loss
    y_pred_data = pinn_net(X_obs_t)
    loss_data = torch.mean((y_pred_data - y_obs_t)**2)

    # PDE loss
    loss_pde = pde_loss_fn(X_colloc, pinn_net)

    # BC loss
    loss_bc_val = bc_loss_fn(pinn_net)

    # Total loss
    loss_total = w_data * loss_data + w_pde * loss_pde + w_bc * loss_bc_val

    loss_total.backward()
    optimizer.step()

    if (it + 1) % 1000 == 0:
        print(f"  iter {it+1:6d}/{N_iter}: total={loss_total.item():.6e}, "
              f"data={loss_data.item():.6e}, pde={loss_pde.item():.6e}, "
              f"bc={loss_bc_val.item():.6e}")

# L-BFGS fine-tuning (wszystkie straty łącznie)
print("\n  L-BFGS fine-tuning...")
lbfgs = torch.optim.LBFGS(
    pinn_net.parameters(),
    max_iter=5000,
    history_size=50,
    line_search_fn="strong_wolfe",
)

def lbfgs_closure():
    lbfgs.zero_grad()
    y_pred_data = pinn_net(X_obs_t)
    loss_data = torch.mean((y_pred_data - y_obs_t)**2)
    loss_pde = pde_loss_fn(X_colloc, pinn_net)
    loss_bc_val = bc_loss_fn(pinn_net)
    loss_total = w_data * loss_data + w_pde * loss_pde + w_bc * loss_bc_val
    loss_total.backward()
    return loss_total

lbfgs.step(lbfgs_closure)

print("\nKrok 4: Końcowa ocena")
print()

# ============================================================
# EWALUACJA
# ============================================================
print("Ewaluacja na danych treningowych...")
pinn_net.eval()
pinn_net = pinn_net.to("cpu")
with torch.no_grad():
    y_pred = pinn_net(torch.tensor(X_obs, dtype=torch.float64)).cpu().numpy()
A_pred = y_pred[:, 0] * A_scale
Q_pred = y_pred[:, 1] * Q_scale

err_A = np.abs(A_pred - A_obs) / (np.max(A_obs) - np.min(A_obs) + 1e-12)
err_Q = np.abs(Q_pred - Q_obs) / (np.max(Q_obs) - np.min(Q_obs) + 1e-12)

print(f"  Normalizowany błąd A: mean={np.mean(err_A):.4f}, max={np.max(err_A):.4f}")
print(f"  Normalizowany błąd Q: mean={np.mean(err_Q):.4f}, max={np.max(err_Q):.4f}")
print()

# Ewaluacja BC
print("Ewaluacja warunków brzegowych...")
with torch.no_grad():
    y_inlet_pred = pinn_net(torch.tensor(X_inlet, dtype=torch.float64)).cpu().numpy()
Q_inlet_pred = y_inlet_pred[:, 1] * Q_scale
err_inlet_Q = np.abs(Q_inlet_pred - Q_inlet_target[:, 0])
print(f"  Inlet BC Q: mean_err={np.mean(err_inlet_Q):.4e}, max_err={np.max(err_inlet_Q):.4e}")

y_out_d1_pred = pinn_net(torch.tensor(X_outlet_d1, dtype=torch.float64)).cpu().numpy()
A_od1 = y_out_d1_pred[:, 0] * A_scale
Q_od1 = y_out_d1_pred[:, 1] * Q_scale
c_d1_pred = np.sqrt(beta_d1 * np.maximum(A_od1, 1e-12) / rho)
u_d1_pred = Q_od1 / np.maximum(A_od1, 1e-12)
W2_d1_pred = u_d1_pred - 2.0 * c_d1_pred
err_W2_d1 = np.abs(W2_d1_pred - W2_0_d1)
print(f"  Outlet BC d1 W2: mean_err={np.mean(err_W2_d1):.4e}, max_err={np.max(err_W2_d1):.4e}")

y_out_d2_pred = pinn_net(torch.tensor(X_outlet_d2, dtype=torch.float64)).cpu().numpy()
A_od2 = y_out_d2_pred[:, 0] * A_scale
Q_od2 = y_out_d2_pred[:, 1] * Q_scale
c_d2_pred = np.sqrt(beta_d2 * np.maximum(A_od2, 1e-12) / rho)
u_d2_pred = Q_od2 / np.maximum(A_od2, 1e-12)
W2_d2_pred = u_d2_pred - 2.0 * c_d2_pred
err_W2_d2 = np.abs(W2_d2_pred - W2_0_d2)
print(f"  Outlet BC d2 W2: mean_err={np.mean(err_W2_d2):.4e}, max_err={np.max(err_W2_d2):.4e}")

y_junc_p_pred = pinn_net(torch.tensor(X_junction_p, dtype=torch.float64)).cpu().numpy()
y_junc_d1_pred = pinn_net(torch.tensor(X_junction_d1, dtype=torch.float64)).cpu().numpy()
y_junc_d2_pred = pinn_net(torch.tensor(X_junction_d2, dtype=torch.float64)).cpu().numpy()
Q_jp = y_junc_p_pred[:, 1] * Q_scale
Q_jd1 = y_junc_d1_pred[:, 1] * Q_scale
Q_jd2 = y_junc_d2_pred[:, 1] * Q_scale
err_mass = np.abs(Q_jp - Q_jd1 - Q_jd2)
print(f"  Junction mass conservation: mean_err={np.mean(err_mass):.4e}, max_err={np.max(err_mass):.4e}")

print()

# ============================================================
# ZAPIS MODELU
# ============================================================
model.net = pinn_net
model.save("pinn_blood_flow_model")
print("Model zapisany jako pinn_blood_flow_model")

# ============================================================
# PREDYKCJA
# ============================================================
print("\nGenerowanie predykcji na siatce...")
Nt_grid = 100
Nz_grid = 50
t_grid = np.linspace(0, T_out, Nt_grid)
z_norm = np.linspace(0, 1, Nz_grid)
t_grid_norm = t_grid / T_scale

rows = []
for i, t_val in enumerate(t_grid):
    for z_val in z_norm:
        for vid, (L, name) in enumerate([
            (L_p, "parent"), (L_d1, "daughter1"), (L_d2, "daughter2")
        ]):
            onehot = [1, 0, 0] if vid == 0 else ([0, 1, 0] if vid == 1 else [0, 0, 1])
            x_in = np.array([[t_grid_norm[i], z_val, *onehot]], dtype=np.float64)
            with torch.no_grad():
                y_out = pinn_net(torch.tensor(x_in, dtype=torch.float64)).cpu().numpy()
            rows.append([t_val, z_val * L, name,
                         float(y_out[0, 0] * A_scale), float(y_out[0, 1] * Q_scale)])

    if (i + 1) % 25 == 0:
        print(f"  Predykcja: {i+1}/{Nt_grid}")

df_pred = pd.DataFrame(rows, columns=["t", "z", "vessel", "A", "Q"])
df_pred.to_csv("pinn_prediction.csv", index=False)
print("Zapisano pinn_prediction.csv")

print("\nGotowe!")